stages:
  - build
  - test
  - deploy

variables:
  DOCKER_TLS_CERTDIR: ""
  APP: "jamel"
  CLIENT: "client"
  SERVER: "server"

build-dev:
  stage: build
  services:
    - git.codenrock.com:5050/sovkombank-securehack-1331/cnrprod1733496609-team-81653/jamel/docker:dind
  image: git.codenrock.com:5050/sovkombank-securehack-1331/cnrprod1733496609-team-81653/jamel/docker:latest
  before_script:
    - echo $DOCKER_ACCESS_TOKEN | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker info
  script:
    - docker build -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$APP-$CLIENT:$CI_COMMIT_SHORT_SHA
      -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$APP-$CLIENT:dev -f Dockerfile.client .
    - docker build -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$APP-$SERVER:$CI_COMMIT_SHORT_SHA
      -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$APP-$SERVER:dev  -f Dockerfile.server .
    - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$APP-$CLIENT --all-tags
    - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$APP-$SERVER --all-tags
  tags:
    - builder
    - git.codenrock.com
  only:
    - dev

build-main:
  stage: build
  services:
    - git.codenrock.com:5050/sovkombank-securehack-1331/cnrprod1733496609-team-81653/jamel/docker:dind
  image: git.codenrock.com:5050/sovkombank-securehack-1331/cnrprod1733496609-team-81653/jamel/docker:latest
  before_script:
    - echo $DOCKER_ACCESS_TOKEN | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker info
  script:
    - docker build -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$APP-$CLIENT:$CI_COMMIT_SHORT_SHA
      -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$APP-$CLIENT:latest -f Dockerfile.client .
    - docker build -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$APP-$SERVER:$CI_COMMIT_SHORT_SHA
      -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$APP-$SERVER:latest  -f Dockerfile.server .
    - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$APP-$CLIENT --all-tags
    - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$APP-$SERVER --all-tags
  tags:
    - builder
    - git.codenrock.com
  only:
    - main

build-admin:
  stage: build
  image: golang:1.23.4-alpine
  before_script:
    - apk add --no-cache make binutils
  script:
    - make release
  artifacts:
    paths:
      - bin/*
    expire_in: 1 week
  tags:
    - builder
    - git.codenrock.com

check-admin:
  stage: test
  services:
    - git.codenrock.com:5050/sovkombank-securehack-1331/cnrprod1733496609-team-81653/jamel/docker:dind
  image: git.codenrock.com:5050/sovkombank-securehack-1331/cnrprod1733496609-team-81653/jamel/docker:latest
  before_script:
    - echo $DOCKER_ACCESS_TOKEN | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker info
    - docker pull ubuntu:latest
    - docker save -o ubuntu.tar ubuntu:latest
  script:
    - chmod +x ./test.sh && chmod +x ./bin/jamel-admin_linux
    - docker-compose -f docker-compose.dev.yaml up -d
    - for i in {0..20}; do
      ./bin/jamel-admin_linux ubuntu.tar &
      done
  dependencies:
    - build-admin
  tags:
    - builder
    - git.codenrock.com

# deploy-dev:
#   variables:
#     DOCKER_HOST: "unix:///var/run/docker.sock"
#     DOCKER_TLS_CERTDIR: ""
#   stage: deploy
#   image: git.codenrock.com:5050/sovkombank-securehack-1331/cnrprod1733496609-team-81653/jamel/docker:latest
#   before_script:
#     - echo $DOCKER_ACCESS_TOKEN | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
#     - docker info
#   script:
#     - echo "Starting services with docker-compose..."
#     - docker-compose -f docker-compose.dev.yaml pull
#     - docker-compose -f docker-compose.dev.yaml up -d
#     - docker-compose -f docker-compose.dev.yaml ps
#   dependencies:
#     - check-admin
#   only:
#     - dev
#   tags:
#     - builder

# deploy-prod:
#   variables:
#     DOCKER_HOST: "unix:///var/run/docker.sock"
#     DOCKER_TLS_CERTDIR: ""
#   stage: deploy
#   image: git.codenrock.com:5050/sovkombank-securehack-1331/cnrprod1733496609-team-81653/jamel/docker:latest
#   before_script:
#     - echo $DOCKER_ACCESS_TOKEN | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
#     - docker info
#   script:
#     - echo "Starting services with docker-compose..."
#     - docker-compose -f docker-compose.yaml pull
#     - docker-compose -f docker-compose.yaml up -d
#     - docker-compose -f docker-compose.yaml ps
#   dependencies:
#     - check-admin
#   only:
#     - main
#   tags:
#     - builder