stages:
  - build
  - test

variables:
  DOCKER_TLS_CERTDIR: ""
  APP: "jamel"
  CLIENT: "client"
  SERVER: "server"

build-dev:
  stage: build
  services:
    - docker:dind
  image: docker:latest
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker info
  script:
    - docker build -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$APP-$CLIENT:$CI_COMMIT_SHORT_SHA
      -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$APP-$CLIENT:dev -f Dockerfile.client .
    - docker build -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$APP-$SERVER:$CI_COMMIT_SHORT_SHA
      -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$APP-$SERVER:dev  -f Dockerfile.server .
    - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$APP-$CLIENT --all-tags
    - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$APP-$SERVER --all-tags
  tags:
    - builder
  only:
    - dev

build-main:
  stage: build
  services:
    - docker:dind
  image: docker:latest
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker info
  script:
    - docker build -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$APP-$CLIENT:$CI_COMMIT_SHORT_SHA
      -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$APP-$CLIENT:latest -f Dockerfile.client .
    - docker build -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$APP-$SERVER:$CI_COMMIT_SHORT_SHA
      -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$APP-$SERVER:latest  -f Dockerfile.server .
    - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$APP-$CLIENT --all-tags
    - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$APP-$SERVER --all-tags
  tags:
    - builder
  only:
    - main

build-admin:
  stage: build
  image: golang:1.23.4-alpine
  before_script:
    - apk add --no-cache make
  script:
    - make build-admin
  artifacts:
    paths:
      - bin/jamel-admin
    expire_in: 1 week
  tags:
    - builder

check-admin:
  stage: test
  services:
    - docker:dind
  image: docker:latest
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker info
    - docker pull ubuntu:latest
    - docker save -o ubuntu.tar ubuntu:latest
  script:
    - chmod +x ./test.sh && chmod +x ./bin/jamel-admin
    - docker-compose -f docker-compose.dev.yaml up -d
    - for i in {0..20}; do
      ./bin/jamel-admin ubuntu.tar &
      done
  dependencies:
    - build-admin
  tags:
    - builder
  