FROM golang:1.23.4-alpine AS builder
WORKDIR /go/src/app
COPY . .

RUN apk add --no-cache make 
RUN make build-server


FROM alpine:3.21
WORKDIR /app
COPY --from=builder /go/src/app/bin/jamel-server /app/jamel-server

ENTRYPOINT [ "./jamel-server" ]
